### ISSUE TITLE
The use of PSBT in the spec would have big advantages

### ISSUE THREAD

**Issue by NicolasDorier** [discreetlogcontracts/dlcspecs#67]
I think the spec could dramatically simplified, as well as allow other existing tooling to interact more easily.

Right now in the messages are exchanged:

In Offer:
* Pubkey
* Funding inputs
* Change
* Total collateral
* FeeRate

In Accept:
* Pubkey
* Funding inputs
* Change
* Total collateral

All of those informations could be replaced by two partial funding PSBTs (one in Accept and One in Offer) which can then be combined for having the funding PSBT.

Since Offer does not know the address of the funding before hand, we could just have a dummy address in the protocol acting as temporary.

1. Any Bitcoin Wallets with PSBT features will have the capability to create those partial PSBTs out of the box without any change.
2. This allows additional flexibility for the parties to bundle a bunch of payments in the funding
3. Scaling to multiple party is easy. (everyone do their funding PSBT with their favorite wallet and share between themselves)
4. This allow each party to decide how much fee to fund to the funding transaction.
5. The remove the need of specifying in the protocol how to exactly calculate the weight of the transaction.

There is some check on the validity of the PSBT that need to be done, but those should be relatively minor.

**Comment by nkohen** [comment]
In bitcoin-s we actually do use PSBTs as the back-end data structure when dealing with DLC Txs, but the main reason they haven't been included in the spec is because they can get massive (which is the main reason I've never been a huge fan of the spec).

I am totally open to the idea of adding PSBTs to the spec but I'd be very concerned about a significant increase in the size of P2P messages, especially seeing as each party need not verify the entirety of the previous txs associated with funding inputs that aren't theirs (a more minimal verification is all that is required). If I turn out to be wrong on this front then I'd be happy to rework things to use PSBTs. (I'm also assuming that the clunkiness of PSBT is the reason lightning doesn't use them (not even in dual funding proposal))

**Comment by NicolasDorier** [comment]
The previous transactions, they don't need to be included at all, legacy or segwit funding, only the `witness_utxo` is enough.

I don't believe dismissing PSBT for the corner case of making a big funding tx happen in practice. (And if it happens, nothing really bad happen)

**Comment by NicolasDorier** [comment]
To be clear, it does not need to be done for next week. But I think that if this is meant to be a standard, the participants should have the maximum flexibility and the standard should take minimum assumption over how the  funding transaction look.

If say both lightning and bitcoin-s were using PSBT, then it would be possible out of the box to make a transaction funding a channel and making a DLC at the same time with standard CLI and even batching payments with wallet with PSBT supports.

And I think it makes the spec leaner, and implementation easier.

**Comment by NicolasDorier** [comment]
I am reading https://github.com/discreetlogcontracts/dlcspecs/pull/57

I think that using PSBT will get rid of all the "expected weight" and fee calculation.

**Comment by ariard** [comment]
I think even using PSBT doesn't save you to compute weight and fee calculation as every participant need to agree on feerate to avoid a free-rider behavior from the lowest-feerate contributor. If you a fair fee model, you need to track the weight of each party contribution and ensure such contribution commit to the negotiated feerate.

Note also, IMO we need to agree on input/output order otherwise we need to sign every pair as SIGHASH_SINGLE, which is a malleability vector and make pinning easier. And you don't want unconfirmed input.

With regards to flexiblity/multi-party I expect than supporting the LN's dual-channel proposal will give us all these advantages. And I think we would like to avoid diverging from then to facilitate offchain support in the future.

If you want the gain of PSBTs, nothing prevent you to have an interface between your DLC stack and your PSBTs signers. That way you can build a DLC funding between different parties and appear as one participant in a DLC flow.

**Comment by NicolasDorier** [comment]
Closing this one. Using PSBT in the protocol seems controversial.
And @nkohen seems to have something in the pipe so users don't have to agree on complicated algorithms to evaluate transaction size.
